### PR TITLE
Chauhan/component handlers

### PR DESCRIPTION
**Pull request by i-am-chauhan**

### CODE REVIEW

**Comment by jasonweiss** [comment]
What is the holdup on this? @i-am-chauhan @mushtaq

**Comment by jasonweiss** [comment]
Ah I see in the JIRA story you are waiting for input from @kgillies and I.  Will get back to you.

**Comment by jasonweiss** [comment]
@i-am-chauhan I would like to see an example in the docs for testing on how to create an "anonymous" assembly/hcd on the fly using DefaultComponentHandlers.  Could you please add this?

**Comment by i-am-chauhan** [comment]
Hi @jasonweiss , we have added the documentation on how to use DefaultComponentHandlers in `Adding Unit Tests` section of paradox docs.

Please provide your input so we can merge this branch.

**Comment by jasonweiss** [comment]
Thanks for adding the example.  I'm assuming all those other commits were a result of a rebase.  I'll merge.

**Pull request merged**
